sudo: required
services:
  - docker

before_install:
  - docker build -t aziz/docker-react -f Dockerfile.dev .

script:
  - docker run aziz/docker-react npm run test -- --coverage

# The bucket_path before any deployment has to be same as app
# on branch master means only take changes for deployment when
# on master branch

# To your existing user, add BeanStalk full access
# Create Env variables on Travis for acc keys

# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker"
#   env: "Docker-env"
#   bucket_name: "elasticbeanstalk-us-west-2-306476627547"
#   bucket_path: "docker"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"

  